// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyAbroad.Models;

#nullable disable

namespace StudyAbroad.Migrations
{
    [DbContext(typeof(AbroadContext))]
    partial class AbroadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyAbroad.Models.Institution", b =>
                {
                    b.Property<int>("InstitutionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstitutionID");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            InstitutionID = 1,
                            Country = "United States",
                            Education = 3,
                            Name = "Northwestern Michigan College",
                            Region = "Michigan",
                            Type = 0,
                            URL = "https://www.nmc.edu/"
                        },
                        new
                        {
                            InstitutionID = 2,
                            Country = "Canada",
                            Education = 3,
                            Name = "Georgian College",
                            Region = "Ontario",
                            Type = 0,
                            URL = "https://www.georgiancollege.ca/"
                        },
                        new
                        {
                            InstitutionID = 3,
                            Country = "Philippines",
                            Education = 3,
                            Name = "Enderun Colleges",
                            Region = "National Capital Region",
                            Type = 1,
                            URL = "https://www.enderuncolleges.com/"
                        },
                        new
                        {
                            InstitutionID = 4,
                            Country = "United Kingdom",
                            Education = 4,
                            Name = "Regents University London",
                            Region = "Greater London",
                            Type = 1,
                            URL = "https://www.regents.ac.uk/"
                        },
                        new
                        {
                            InstitutionID = 5,
                            Country = "Ireland",
                            Education = 4,
                            Name = "University of Limerick",
                            Region = "Munster",
                            Type = 0,
                            URL = "https://www.ul.ie/"
                        },
                        new
                        {
                            InstitutionID = 6,
                            Country = "Germany",
                            Education = 4,
                            Name = "Private University of Applied Sciences, Goettingen",
                            Region = "Niedersachsen",
                            Type = 1,
                            URL = "https://www.pfh.de/en"
                        },
                        new
                        {
                            InstitutionID = 7,
                            Country = "Japan",
                            Education = 1,
                            Name = "Musashino Higashi Middle School",
                            Region = "Tokyo",
                            Type = 1,
                            URL = "https://www.musashino-higashi.org/chugaku/"
                        },
                        new
                        {
                            InstitutionID = 8,
                            Country = "Japan",
                            Education = 2,
                            Name = "International College of Technology, Kanazawa",
                            Region = "Ishikawa",
                            Type = 1,
                            URL = "https://www.ict-kanazawa.ac.jp/"
                        },
                        new
                        {
                            InstitutionID = 9,
                            Country = "Japan",
                            Education = 2,
                            Name = "Toin Gakuen",
                            Region = "Kanagawa",
                            Type = 1,
                            URL = "https://toin.ac.jp/ses/"
                        },
                        new
                        {
                            InstitutionID = 10,
                            Country = "Japan",
                            Education = 4,
                            Name = "University of Tokyo",
                            Region = "Tokyo",
                            Type = 0,
                            URL = "https://www.u-tokyo.ac.jp/ja/index.html"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
